// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simresult_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_simresult_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_simresult_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_simresult_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_simresult_5fmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_simresult_5fmsg_2eproto;
namespace MA3 {
class SimResult;
class SimResultDefaultTypeInternal;
extern SimResultDefaultTypeInternal _SimResult_default_instance_;
}  // namespace MA3
PROTOBUF_NAMESPACE_OPEN
template<> ::MA3::SimResult* Arena::CreateMaybeMessage<::MA3::SimResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace MA3 {

// ===================================================================

class SimResult PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MA3.SimResult) */ {
 public:
  inline SimResult() : SimResult(nullptr) {}
  virtual ~SimResult();

  SimResult(const SimResult& from);
  SimResult(SimResult&& from) noexcept
    : SimResult() {
    *this = ::std::move(from);
  }

  inline SimResult& operator=(const SimResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimResult& operator=(SimResult&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SimResult& default_instance();

  static inline const SimResult* internal_default_instance() {
    return reinterpret_cast<const SimResult*>(
               &_SimResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SimResult& a, SimResult& b) {
    a.Swap(&b);
  }
  inline void Swap(SimResult* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SimResult* New() const final {
    return CreateMaybeMessage<SimResult>(nullptr);
  }

  SimResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SimResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SimResult& from);
  void MergeFrom(const SimResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MA3.SimResult";
  }
  protected:
  explicit SimResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_simresult_5fmsg_2eproto);
    return ::descriptor_table_simresult_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEdgeCostFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // double edge_cost = 2;
  void clear_edge_cost();
  double edge_cost() const;
  void set_edge_cost(double value);
  private:
  double _internal_edge_cost() const;
  void _internal_set_edge_cost(double value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:MA3.SimResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double edge_cost_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_simresult_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SimResult

// bool success = 1;
inline void SimResult::clear_success() {
  success_ = false;
}
inline bool SimResult::_internal_success() const {
  return success_;
}
inline bool SimResult::success() const {
  // @@protoc_insertion_point(field_get:MA3.SimResult.success)
  return _internal_success();
}
inline void SimResult::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void SimResult::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:MA3.SimResult.success)
}

// double edge_cost = 2;
inline void SimResult::clear_edge_cost() {
  edge_cost_ = 0;
}
inline double SimResult::_internal_edge_cost() const {
  return edge_cost_;
}
inline double SimResult::edge_cost() const {
  // @@protoc_insertion_point(field_get:MA3.SimResult.edge_cost)
  return _internal_edge_cost();
}
inline void SimResult::_internal_set_edge_cost(double value) {
  
  edge_cost_ = value;
}
inline void SimResult::set_edge_cost(double value) {
  _internal_set_edge_cost(value);
  // @@protoc_insertion_point(field_set:MA3.SimResult.edge_cost)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MA3

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_simresult_5fmsg_2eproto
