// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: querysim_msg.proto

#include "querysim_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace MA3 {
class QuerySimDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<QuerySim> _instance;
} _QuerySim_default_instance_;
}  // namespace MA3
static void InitDefaultsscc_info_QuerySim_querysim_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MA3::_QuerySim_default_instance_;
    new (ptr) ::MA3::QuerySim();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_QuerySim_querysim_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_QuerySim_querysim_5fmsg_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_querysim_5fmsg_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_querysim_5fmsg_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_querysim_5fmsg_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_querysim_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, mdx_),
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, mdy_),
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, start_x_),
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, start_y_),
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, start_theta_),
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, vertex_id_),
  PROTOBUF_FIELD_OFFSET(::MA3::QuerySim, mprim_id_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MA3::QuerySim)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MA3::_QuerySim_default_instance_),
};

const char descriptor_table_protodef_querysim_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022querysim_msg.proto\022\003MA3\"\200\001\n\010QuerySim\022\013"
  "\n\003mdx\030\001 \001(\002\022\013\n\003mdy\030\002 \001(\002\022\017\n\007start_x\030\003 \001("
  "\002\022\017\n\007start_y\030\004 \001(\002\022\023\n\013start_theta\030\005 \001(\002\022"
  "\021\n\tvertex_id\030\006 \001(\r\022\020\n\010mprim_id\030\007 \001(\rb\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_querysim_5fmsg_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_querysim_5fmsg_2eproto_sccs[1] = {
  &scc_info_QuerySim_querysim_5fmsg_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_querysim_5fmsg_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_querysim_5fmsg_2eproto = {
  false, false, descriptor_table_protodef_querysim_5fmsg_2eproto, "querysim_msg.proto", 164,
  &descriptor_table_querysim_5fmsg_2eproto_once, descriptor_table_querysim_5fmsg_2eproto_sccs, descriptor_table_querysim_5fmsg_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_querysim_5fmsg_2eproto::offsets,
  file_level_metadata_querysim_5fmsg_2eproto, 1, file_level_enum_descriptors_querysim_5fmsg_2eproto, file_level_service_descriptors_querysim_5fmsg_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_querysim_5fmsg_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_querysim_5fmsg_2eproto)), true);
namespace MA3 {

// ===================================================================

class QuerySim::_Internal {
 public:
};

QuerySim::QuerySim(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MA3.QuerySim)
}
QuerySim::QuerySim(const QuerySim& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&mdx_, &from.mdx_,
    static_cast<size_t>(reinterpret_cast<char*>(&mprim_id_) -
    reinterpret_cast<char*>(&mdx_)) + sizeof(mprim_id_));
  // @@protoc_insertion_point(copy_constructor:MA3.QuerySim)
}

void QuerySim::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&mdx_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&mprim_id_) -
      reinterpret_cast<char*>(&mdx_)) + sizeof(mprim_id_));
}

QuerySim::~QuerySim() {
  // @@protoc_insertion_point(destructor:MA3.QuerySim)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void QuerySim::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void QuerySim::ArenaDtor(void* object) {
  QuerySim* _this = reinterpret_cast< QuerySim* >(object);
  (void)_this;
}
void QuerySim::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void QuerySim::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const QuerySim& QuerySim::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_QuerySim_querysim_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void QuerySim::Clear() {
// @@protoc_insertion_point(message_clear_start:MA3.QuerySim)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&mdx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mprim_id_) -
      reinterpret_cast<char*>(&mdx_)) + sizeof(mprim_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QuerySim::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float mdx = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          mdx_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float mdy = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          mdy_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float start_x = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          start_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float start_y = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          start_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float start_theta = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          start_theta_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // uint32 vertex_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          vertex_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 mprim_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          mprim_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* QuerySim::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MA3.QuerySim)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float mdx = 1;
  if (!(this->mdx() <= 0 && this->mdx() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_mdx(), target);
  }

  // float mdy = 2;
  if (!(this->mdy() <= 0 && this->mdy() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_mdy(), target);
  }

  // float start_x = 3;
  if (!(this->start_x() <= 0 && this->start_x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_start_x(), target);
  }

  // float start_y = 4;
  if (!(this->start_y() <= 0 && this->start_y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_start_y(), target);
  }

  // float start_theta = 5;
  if (!(this->start_theta() <= 0 && this->start_theta() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_start_theta(), target);
  }

  // uint32 vertex_id = 6;
  if (this->vertex_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_vertex_id(), target);
  }

  // uint32 mprim_id = 7;
  if (this->mprim_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_mprim_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MA3.QuerySim)
  return target;
}

size_t QuerySim::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MA3.QuerySim)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float mdx = 1;
  if (!(this->mdx() <= 0 && this->mdx() >= 0)) {
    total_size += 1 + 4;
  }

  // float mdy = 2;
  if (!(this->mdy() <= 0 && this->mdy() >= 0)) {
    total_size += 1 + 4;
  }

  // float start_x = 3;
  if (!(this->start_x() <= 0 && this->start_x() >= 0)) {
    total_size += 1 + 4;
  }

  // float start_y = 4;
  if (!(this->start_y() <= 0 && this->start_y() >= 0)) {
    total_size += 1 + 4;
  }

  // float start_theta = 5;
  if (!(this->start_theta() <= 0 && this->start_theta() >= 0)) {
    total_size += 1 + 4;
  }

  // uint32 vertex_id = 6;
  if (this->vertex_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_vertex_id());
  }

  // uint32 mprim_id = 7;
  if (this->mprim_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_mprim_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void QuerySim::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MA3.QuerySim)
  GOOGLE_DCHECK_NE(&from, this);
  const QuerySim* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<QuerySim>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MA3.QuerySim)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MA3.QuerySim)
    MergeFrom(*source);
  }
}

void QuerySim::MergeFrom(const QuerySim& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MA3.QuerySim)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.mdx() <= 0 && from.mdx() >= 0)) {
    _internal_set_mdx(from._internal_mdx());
  }
  if (!(from.mdy() <= 0 && from.mdy() >= 0)) {
    _internal_set_mdy(from._internal_mdy());
  }
  if (!(from.start_x() <= 0 && from.start_x() >= 0)) {
    _internal_set_start_x(from._internal_start_x());
  }
  if (!(from.start_y() <= 0 && from.start_y() >= 0)) {
    _internal_set_start_y(from._internal_start_y());
  }
  if (!(from.start_theta() <= 0 && from.start_theta() >= 0)) {
    _internal_set_start_theta(from._internal_start_theta());
  }
  if (from.vertex_id() != 0) {
    _internal_set_vertex_id(from._internal_vertex_id());
  }
  if (from.mprim_id() != 0) {
    _internal_set_mprim_id(from._internal_mprim_id());
  }
}

void QuerySim::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MA3.QuerySim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QuerySim::CopyFrom(const QuerySim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MA3.QuerySim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuerySim::IsInitialized() const {
  return true;
}

void QuerySim::InternalSwap(QuerySim* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QuerySim, mprim_id_)
      + sizeof(QuerySim::mprim_id_)
      - PROTOBUF_FIELD_OFFSET(QuerySim, mdx_)>(
          reinterpret_cast<char*>(&mdx_),
          reinterpret_cast<char*>(&other->mdx_));
}

::PROTOBUF_NAMESPACE_ID::Metadata QuerySim::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MA3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MA3::QuerySim* Arena::CreateMaybeMessage< ::MA3::QuerySim >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MA3::QuerySim >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
